name: Linux CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['9.2.3']
        cabal: ['3.6.2.0']
        
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
        
    - name: Freeze
      run: |
        cabal freeze
    - name: Cache cabal
      uses: actions/cache@v2
      id: cache-cabal
      with:
        path: '~/.cabal'
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('/home/runner/work/tidal-gui/tidal-gui/src') }}-1
        
    - name: Cache dist
      uses: actions/cache@v2
      id: cache-bin
      with:
        path: '/dist-newstyle/'
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('/home/runner/work/tidal-gui/tidal-gui/src') }}-2
    
    - name: cabal update and build
      run: | 
            cabal update
            cabal v2-build --enable-tests
    
    - name : make directory
      run: |
            mkdir binary
            mkdir binary/haskell-libs/
            mkdir binary/c-libs/
            
    - name: move GHC libs and configs
      run: |
            mkdir binary/haskell-libs/ghc-packages/
            cd ${{ steps.setup-haskell-cabal.outputs.ghc-path }}
            cd ..
            cd lib
            cp -r ghc-${{ matrix.ghc }}/* /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/ghc-packages
            
    - name: move installed packages
      run: | 
            mkdir binary/haskell-libs/packages/
            cp -r ${{ steps.setup-haskell-cabal.outputs.cabal-store }}/ghc-${{ matrix.ghc }}/* binary/haskell-libs/packages
            ls binary/haskell-libs/packages
   
    - name: change paths in config files (GHC)
      run: |
            mv /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/ghc-packages/package.conf.d /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/package.conf.d
            sed -i 's/\/usr\/local\/.ghcup\/ghc\/${{ matrix.ghc }}\/lib\/ghc-${{ matrix.ghc }}/${pkgroot}\/ghc-packages/g' /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/package.conf.d/*
     
    - name: change paths in config files (cabal)
      run: |
            mv /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/packages/package.db /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/package.db
            sed -i 's/\/home\/runner\/.cabal\/store\/ghc-${{ matrix.ghc }}/${pkgroot}\/packages/g' /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/package.db/*
   
    - name: move ghc settings etc
      run: |
            mv /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/ghc-packages/settings /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/settings
            mv /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/ghc-packages/llvm-targets /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/llvm-targets
            mv /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/ghc-packages/llvm-passes /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/llvm-passes
            
    - name: ghc-pkg recache
      run: |
            ghc-pkg --package-db=/home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/package.conf.d recache
            ghc-pkg --package-db=/home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/package.db recache
            ghc-pkg --package-db=/home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/package.conf.d --package-db=/home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/package.db check
   
    - name: move c-libs
      run: |
            cp /usr/lib/x86_64-linux-gnu/libz.so.1             /home/runner/work/tidal-gui/tidal-gui/binary/c-libs/libz.so.1 
            cp /usr/lib/x86_64-linux-gnu/libtinfo.so.6         /home/runner/work/tidal-gui/tidal-gui/binary/c-libs/libtinfo.so.6  
            cp /usr/lib/x86_64-linux-gnu/librt.so.1            /home/runner/work/tidal-gui/tidal-gui/binary/c-libs/librt.so.1  
            cp /usr/lib/x86_64-linux-gnu/libutil.so.1          /home/runner/work/tidal-gui/tidal-gui/binary/c-libs/libutil.so.1
            cp /usr/lib/x86_64-linux-gnu/libpthread.so.0       /home/runner/work/tidal-gui/tidal-gui/binary/c-libs/libpthread.so.0 
            cp /usr/lib/x86_64-linux-gnu/libm.so.6             /home/runner/work/tidal-gui/tidal-gui/binary/c-libs/libm.so.6
            cp /usr/lib/x86_64-linux-gnu/libgmp.so.10          /home/runner/work/tidal-gui/tidal-gui/binary/c-libs/libgmp.so.10 
            cp /usr/lib/x86_64-linux-gnu/libc.so.6             /home/runner/work/tidal-gui/tidal-gui/binary/c-libs/libc.so.6 
            cp /usr/lib/x86_64-linux-gnu/libdl.so.2            /home/runner/work/tidal-gui/tidal-gui/binary/c-libs/libdl.so.2  
            ln -s /usr/lib/x86_64-linux-gnu/libz.so.1          /home/runner/work/tidal-gui/tidal-gui/binary/c-libs/libz.so
            ln -s /usr/lib/x86_64-linux-gnu/libtinfo.so.6      /home/runner/work/tidal-gui/tidal-gui/binary/c-libs/libtinfo.so
            ln -s /usr/lib/x86_64-linux-gnu/librt.so.1         /home/runner/work/tidal-gui/tidal-gui/binary/c-libs/librt.so
            ln -s /usr/lib/x86_64-linux-gnu/libutil.so.1       /home/runner/work/tidal-gui/tidal-gui/binary/c-libs/libutil.so
            ln -s /usr/lib/x86_64-linux-gnu/libpthread.so.0    /home/runner/work/tidal-gui/tidal-gui/binary/c-libs/libpthread.so
            ln -s /usr/lib/x86_64-linux-gnu/libm.so.6          /home/runner/work/tidal-gui/tidal-gui/binary/c-libs/libm.so
            ln -s /usr/lib/x86_64-linux-gnu/libgmp.so.10       /home/runner/work/tidal-gui/tidal-gui/binary/c-libs/libgmp.so
            ln -s /usr/lib/x86_64-linux-gnu/libc.so.6          /home/runner/work/tidal-gui/tidal-gui/binary/c-libs/libc.so
            ln -s /usr/lib/x86_64-linux-gnu/libdl.so.2         /home/runner/work/tidal-gui/tidal-gui/binary/c-libs/libdl.so
   
    - name: remove unneccessary libs 
      run: |
            cd /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/ghc-packages
            # rm -r ghc-${{ matrix.ghc }}
            rm -r Cabal-*
            rm -r rts
            
    - name: fake gcc
      run: |
            mkdir binary/haskell-libs/bin
            cp -r fake_gcc.sh binary/haskell-libs/bin/fake_gcc.sh
            sed -i 's/gcc/$topdir\/bin\/fake_gcc.sh/g' /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/settings
            chmod 755 binary/haskell-libs/bin/fake_gcc.sh
   
    - name: move static
      run: cp -r static binary/static
   
    - name: move executable
      run: cp -r dist-newstyle/build/x86_64-linux/ghc-${{ matrix.ghc }}/tidal-gui-0.1.0.0/x/tidal-gui/build/tidal-gui/tidal-gui binary/tidal-gui
  
   # - name: zip files
   #   run: |
   #         cd /home/runner/work/tidal-gui/tidal-gui/
   #         tar cvfj tidal-linux.tar binary/*
  
   # - name: Release
   #   uses: softprops/action-gh-release@v1
   #   with:
   #       files: /home/runner/work/tidal-gui/tidal-gui/tidal-linux.tar
    
    - name: setup node
      uses: actions/setup-node@v3
      with:
         node-version: 16
    
    - name: electron forge
      run: |
            npm install --save-dev @electron-forge/cli
            npx electron-forge import
            npm run make

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: |
                  out/make/deb/x64/*.deb
                  out/make/rpm/x64/*.rpm
